name: Start Dev Site
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch of eu-rate-boson'
        default: 'develop'
        required: true

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest]
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: xcratch/scratch-gui
          ref: xcratch
          path: ./scratch-gui
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./scratch-gui
      - uses: actions/checkout@v3
        with:
          repository: eu-rate-boson/mbit-more-v2
          ref: ${{github.event.inputs.branch}}
          path: ./mbit-more-v2
          node-version: ${{ matrix.node-version }}
      - run: npm install
        working-directory: ./mbit-more-v2
      - run: npx xcratch-register --id=microbitMore --gui=../scratch-gui --block=./src/vm/extensions/block --entry=./src/gui/lib/libraries/extensions/entry --core --use=extension-support util io --url="https://eu-rate-boson.github.io/dev/dist/microbitMore.mjs"
        working-directory: ./mbit-more-v2
      - run: npx xcratch-build --module=microbitMore --gui=../scratch-gui --block=./src/vm/extensions/block --entry=./src/gui/lib/libraries/extensions/entry --url="https://eu-rate-boson.github.io/dev/dist/microbitMore.mjs"
        working-directory: ./mbit-more-v2
      - uses: actions/checkout@v3
        with:
          repository: eu-rate-boson/eu-rate-boson.github.io
          ref: develop
          path: ./eu-rate-boson.github.io
          node-version: ${{ matrix.node-version }}
      - run: node ./scripts/tailoring.js -gui=../scratch-gui
        working-directory: ./eu-rate-boson.github.io
      - run: npm run build
        working-directory: ./scratch-gui
      - uses: actions/checkout@v3
        with:
          repository: eu-rate-boson/eu-rate-boson.github.io
          path: ./eu-rate-boson.github.io
          node-version: ${{ matrix.node-version }}
      - run: mv -T ./eu-rate-boson.github.io/site ./public
      - run: mv -T ./scratch-gui/build ./public/editor
      - run: mv -T ./mbit-more-v2/dist ./public/dist
      - run: mv -T ./mbit-more-v2/examples ./public/examples
      - uses: actions/checkout@v3
        with:
          repository: eu-rate-boson/microbit-more-doc
          path: ./microbit-more-doc
          node-version: ${{ matrix.node-version }}
      - run: mv -T ./microbit-more-doc/docs ./public/docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          destination_dir: ./dev
          keep_files: false
          node-version: ${{ matrix.node-version }}
